import pandas as pd

list_to_compare = [
    'AXTEL, S.A.B. DE C.V.',
    'CIBANCO,S.A. INSTITUCION DE BANCA MULTIPLE',
    'GRUPO AEROPORTUARIO DEL SURESTE, S.A.B. DE C.V.',
    'COMPAÑIA MINERA AUTLAN, S.A.B. DE C. V.',
    'BANCO NACIONAL DE MÉXICO, S.A.,  INTEGRANTE DEL GRUPO FINANCIERO BANAMEX',
    'CONSORCIO ARISTOS, S.A.B. DE C.V.',
    'CONSORCIO ARA, S.A.B. DE C.V.',
    'BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIPLE, INVEX GRUPO FINANCIERO',
    'WAL - MART DE MEXICO, S.A.B. DE C.V.',
    'VINTE VIVIENDAS INTEGRALES, S.A.B. DE C.V.',
    'VITRO, S.A.B. DE C.V.',
    'CONTROLADORA VUELA COMPAÑÍA DE AVIACIÓN, S.A.B. DE C.V.',
    'VISTA ENERGY, S.A.B. DE C.V.',
    'GRUPO VASCONIA S.A.B.',
    'HSBC MEXICO, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO HSBC',
    'URBI DESARROLLOS URBANOS, S.A.B. DE C.V.',
    'UNIFIN FINANCIERA, S.A.B. DE C.V.',
    'CORPORACIÓN INMOBILIARIA VESTA, S.A.B. DE C.V.',
    'VALUE GRUPO FINANCIERO, S.A.B. DE C.V.',
    'PROTEAK UNO, S.A.B. DE C.V.',
    'TEKCHEM, S.A.B. DE C.V.',
    'GRUPO TMM, S.A.',
    'GRUPO TRAXIÓN S.A.B DE C.V.',
    'TENARIS S.A.',
    'GRUPO TELEVISA, S.A.B.',
    'BANCO MONEX, S.A., INSTITUCION DE BANCA MULTIPLE, MONEX GRUPO FINANCIERO',
    'SEMPRA',
    'GRUPO SPORTS WORLD, S.A.B. DE C.V.',
    'ACTINVER CASA DE BOLSA, S.A. DE C.V., GRUPO FINANCIERO ACTINVER, DIVISIÓN FIDUCIARIA',
    'SCOTIA INVERLAT CASA DE BOLSA. S.A. DE C.V. GRUPO FINANCIERO SCOTIABANK INVERLAT',
    'GRUPO SIMEC, S.A.B. DE C.V.',
    'OPERADORA DE SITES MEXICANOS, S.A.B. DE C.V.',
    'ORGANIZACION SORIANA, S.A.B. DE C.V.',
    'SARE HOLDING, S.A.B. DE C.V.',
    'BANCO SANTANDER, S.A.',
    'SAVIA, S.A. DE C.V.',
    'RLH PROPERTIES, S.A.B. DE C.V.',
    'GRUPO QUMMA, S.A. DE C.V.',
    'THE BANK OF NEW YORK MELLON, S.A., INSTITUCION DE BANCA MULTIPLE',
    'REGIONAL, S.A.B. DE C.V.',
    'GRUPO RADIO CENTRO, S.A.B. DE C.V.',
    'PEÑA VERDE S.A.B.',
    'QUÁLITAS CONTROLADORA, S.A.B. DE C.V.',
    'Q.B. INDUSTRIAS, S.A. DE C.V.',
    'PROCORP, S.A.B. DE C.V.',
    'GRUPO POSADAS, S.A.B. DE C.V.',
    'PLANIGRUPO LATAM, S.A.B. DE C.V.',
    'GRUPO POCHTECA, S.A.B. DE C.V.',
    'PROMOTORA Y OPERADORA DE INFRAESTRUCTURA, S.A.B. DE C.V.',
    'INDUSTRIAS PEÑOLES, S. A.B. DE C. V.',
    'PROMOTORA AMBIENTAL, S.A.B. DE C.V.',
    'GRUPO AEROPORTUARIO DEL CENTRO NORTE, S.A.B. DE C.V.',
    'NEMAK, S.A.B. DE C.V.',
    'ORBIA ADVANCE CORPORATION, S.A.B. DE C.V.',
    'NACIONAL FINANCIERA, S.N.C., INSTITUCION DE BANCA DE DESARROLLO',
    'MINERA FRISCO, S.A.B. DE C.V.',
    'BANCO ACTINVER, S.A. INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO ACTINVER',
    'GRUPO MINSA, S.A.B. DE C.V.',
    'MEXCAP, S.A. DE C.V. SINCA',
    'MEGACABLE HOLDINGS, S.A.B. DE C.V.',
    'EL PUERTO DE LIVERPOOL, S.A.B. DE C.V.',
    'MEDICA SUR, S.A.B. DE C.V.',
    'MEXPLUS, S.A. DE C.V. SINCA',
    'GRUPO LAMOSA, S.A.B. DE C.V.',
    'SITIOS LATINOAMÉRICA, S.A.B. DE C.V.',
    'LA LATINOAMERICANA SEGUROS, S.A.',
    'LA COMER S.A.B. DE C.V.',
    'GENOMMA LAB INTERNACIONAL, S.A.B. DE C.V.',
    'GRUPO KUO, S.A.B. DE C.V.',
    'SERVICIOS CORPORATIVOS JAVER, S.A.B. DE C.V.',
    'COCACOLA FEMSA, S.A.B. DE C.V.',
    'KIMBERLY - CLARK DE MEXICO S.A.B. DE C.V.',
    'INVEX CONTROLADORA, S.A.B. DE C.V.',
    'INGEAL, S.A.B. DE C.V.',
    'EMPRESAS ICA, S.A.B. DE C.V.',
    'IMPULSORA DEL DESARROLLO Y EL EMPLEO EN AMERICA LATINA, S.A.B. DE C.V.',
    'INDUSTRIAS CH, S.A.B. DE C.V.',
    'INDUSTRIA AUTOMOTRIZ, S.A. DE C.V.',
    'GRUPO HOTELERO SANTA FE, S.A.B. DE C.V.',
    'DESARROLLADORA HOMEX, S.A.B. DE C.V.',
    'HIMEXSA, S.A.B. DE C.V.',
    'HOTELES CITY EXPRESS, S.A.B. DE C.V.',
    'GRUMA, S.A.B. DE C.V.',
    'GRUPO HERDEZ, S.A.B. DE C.V.',
    'GRUPO PROFUTURO, S.A.B. DE C.V.',
    'GRUPO MEXICO, S.A.B. DE C.V.',
    'GRUPO COMERCIAL GOMO,S.A. DE C.V.',
    'GMÉXICO TRANSPORTES, S.A.B. DE C.V.',
    'GRUPO MEXICANO DE DESARROLLO, S.A.B.',
    'GRUPO PALACIO DE HIERRO, S.A.B. DE C.V.',
    'GRUPO NACIONAL PROVINCIAL, S.A.B.',
    'GRUPO INDUSTRIAL SALTILLO, S.A.B. DE C.V.',
    'GRUPO GICSA, S.A.B. DE C.V.',
    'GRUPO FINANCIERO BANORTE, S.A.B DE C.V.',
    'GENTERA, S.A.B. DE C.V.',
    'GRUPO FINANCIERO MULTIVA S.A.B. DE C.V.',
    'GRUPO FINANCIERO INBURSA, S.A.B. DE C.V.',
    'GRUPO FAMSA, S.A.B. DE C.V.',
    'GRUPO GIGANTE, S.A.B. DE C.V.',
    'INTERCAM BANCO, S.A., INSTITUCIÓN DE BANCA MÚLTIPLE, INTERCAM GRUPO FINANCIERO',
    'GCC, S.A.B. DE C.V.',
    'CORPORATIVO GBM, S.A.B. DE C. V.',
    'GRUPO CARSO, S.A.B. DE C.V.',
    'ACOSTA VERDE, S.A.B. DE C.V.',
    'GRUPO AEROPORTUARIO DEL PACIFICO, S.A.B. DE C.V.',
    'FRESNILLO PLC',
    'CORPORATIVO FRAGUA, S.A.B. DE C.V.',
    'BANCO AZTECA S.A. INSTITUCION DE BANCA MULTIPLE',
    'FINANCIERA INDEPENDENCIA, S.A.B. DE C.V. SOFOM, E.N.R.',
    'CASA DE BOLSA FINAMEX, S.A.B. DE C.V.',
    'FOMENTO ECONÓMICO MEXICANO, S.A.B. DE C.V.',
    'EDOARDOS MARTIN, S.A.B. DE C.V.',
    'GRUPO ELEKTRA, S.A.B. DE C.V.',
    'DINE, S.A.B. DE C.V.',
    'CYDSA, S.A.B. DE C.V.',
    'CONTROLADORA AXTEL, S.A.B. DE C.V.',
    'ORGANIZACIÓN CULTIBA, S.A.B. DE CV',
    'CREDITO REAL, S.A.B. DE C.V., SOFOM, E.N.R.',
    'BECLE, S.A.B. DE C.V.',
    'CMR, S.A.B. DE C.V.',
    'CONVERTIDORA INDUSTRIAL, S.A.B. DE C.V.',
    'CORPORACION MOCTEZUMA, S.A.B. DE C.V.',
    'G COLLADO, S.A.B. DE C.V.',
    'CITIBANAMEX CASA DE BOLSA, S.A. DE C.V. CASA DE BOLSA, INTEGRANTE DEL GRUPO FINANCIERO CITIBANAMEX',
    'CORPORACION INTERAMERICANA DE ENTRETENIMIENTO, S.A.B. DE C.V.',
    'GRUPE, S.A.B. DE C.V.',
    'INTERNACIONAL DE CERAMICA, S.A.B. DE C.V.',
    'GRUPO COMERCIAL CHEDRAUI, S.A.B. DE C.V.',
    'CEMEX, S.A.B. DE C.V.',
    'CORPOVAEL S.A.B. DE C.V.',
    'EMPRESAS CABLEVISION, S.A. DE C.V.',
    'BOLSA MEXICANA DE VALORES, S.A.B. DE C.V.',
    'BANCO SANTANDER MEXICO, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO SANTANDER',
    'GRUPO BIMBO, S.A.B. DE C.V.',
    'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.',
    'FARMACIAS BENAVIDES, S.A.B. DE C.V.',
    'BANCO DEL BAJÍO, S.A., INSTITUCIÓN DE BANCA MÚLTIPLE',
    'TV AZTECA, S.A.B. DE C.V.',
    'INDUSTRIAS BACHOCO, S.A.B. DE C.V.',
    'GRUPO BAFAR, S.A.B. DE C.V.',
    'BBVA MEXICO, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO BBVA MEXICO',
    'ANHEUSER-BUSCH INBEV SA/NV',
    'AMERICA MOVIL, S.A.B. DE C.V.',
    'ALTERNA ASESORIA INTERNACIONAL, S.A.B. DE C.V.',
    'ALEATICA, S.A.B. DE C.V.',
    'ALFA, S.A.B. DE C.V.',
    'ALPEK, S.A.B. DE C.V.',
    'ALSEA, S.A.B. DE C.V.',
    'ALTOS HORNOS DE MEXICO, S.A. DE C.V.',
    'AGRO INDUSTRIAL EXPORTADORA, S.A. DE C.V.',
    'CORPORACION ACTINVER, S.A.B. DE C.V.',
    'GRUPO ROTOPLAS, S.A.B. DE C.V.',
    'ACCEL, S.A.B. DE C.V.',
    'ARCA CONTINENTAL, S.A.B. DE C.V.',
    'ESTADO LIBRE Y SOBERANO DE MÉXICO (GOBIERNO DEL ESTADO DE MEXICO)',
    'FUNDACIÓN RAFAEL DONDÉ, I.A.P.',
    'DESARROLLOS EOLICOS MEXICANOS DE OAXACA 1 SAPI DE CV',
    'DESARROLLOS HIDRÁULICOS DE CANCÚN, S.A. DE C.V.',
    'DAIMLER MEXICO, S.A. DE C.V.',
    'CREDICLUB S.A. DE C.V, S.F.P.',
    'CORPORACIÓN A.G.F., S.A. DE C.V.',
    'BANCO INBURSA, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO INBURSA',
    'XIGNUX, S.A. DE C.V.',
    'VOLKSWAGEN LEASING, S.A. DE C.V.',
    'CORPORACION TAPATIA DE TELEVISION, S.A. DE C.V.',
    'BANCO INTERACCIONES, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO INTERACCIONES',
    'VALUE ARRENDADORA, S.A. DE C.V., SOFOM, E.R.',
    'TOYOTA FINANCIAL SERVICES MEXICO, S.A. DE C.V.',
    'SISTEMA DE CRÉDITO AUTOMOTRIZ S.A. DE C.V.',
    'SOCIEDAD HIPOTECARIA FEDERAL, S.N.C., INSTITUCION DE BANCA DE DESARROLLO',
    'TANNER SERVICIOS FINANCIEROS S.A.',
    'TELEFONOS DE MEXICO, S.A.B. DE C.V.',
    'START BANREGIO, S.A. DE C.V., SOCIEDAD FINANCIERA DE OBJETO MÚLTIPLE, ENTIDAD REGULADA, BANREGIO GRUPO FINANCIERO',
    'SGFP MÉXICO, S.A. DE C.V.',
    'INMOBILIARIA RUBA, S.A. DE C.V.',
    'SOFOPLUS, S.A.P.I. DE C.V., S.O.F.O.M., E.R.',
    'PROMOTORA DE INFRAESTRUCTURA REGISTRAL, S.A. DE C.V., SOFOM., E.N.R.',
    'RED DE CARRETERAS DE OCCIDENTE , S.A.B. DE C.V.',
    'SCOTIABANK INVERLAT, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO SCOTIABANK INVERLAT',
    'BANOBRAS, S.N.C.',
    'PETROLEOS MEXICANOS',
    'PORTAFOLIO DE NEGOCIOS, S.A. DE C.V., SOFOM, E.R.',
    'OPERADORA DE SITES MEXICANOS, S.A. DE C.V.',
    'PACCAR FINANCIAL MEXICO, S.A. DE C.V.',
    'ORGANIZACIÓN DE PROYECTOS DE INFRAESTRUCTURA, S.A.P.I. DE C.V.',
    'NR FINANCE MEXICO, S.A. DE C.V.',
    'NATURGY MÉXICO, SA. DE C.V.',
    'NACIONAL FINANCIERA, S.N.C.',
    'NACIONAL FINANCIERA S.N.C.',
    'NAVISTAR FINANCIAL, S.A. DE C.V., SOFOM, E.R.',
    'MOLIBDENOS Y METALES S.A.',
    'MONTEPIO LUZ SAVIÑON, INSTITUCIÓN DE ASISTENCIA PRIVADA',
    'MERCADER FINANCIAL, S.A., SOFOM, E.R.',
    'GRUPO LALA, S.A.B. DE C.V.',
    'ION FINANCIERA, S.A.P.I. DE C.V., SOFOM, E.R.',
    'BANCO DE EXPORTACIONES E IMPORTACIONES DE COREA',
    'INMUEBLES CARSO, S.A. DE C.V.',
    'INTERNACIONAL DE INVERSIONES S.A.P.I DE C.V.',
    'GRUPO HYC, S.A. DE C.V.',
    'BIENES PROGRAMADOS, S.A. DE C.V.',
    'GRUPO VIVA AEROBUS SA DE CV',
    'GRUPO SANBORNS, S.A.B. DE C.V.',
    'GM FINANCIAL DE MEXICO, S.A. DE C.V., SOFOM E.R.',
    'PROMOTORA EMPRESARIAL DEL NORTE, S.A. DE C.V.',
    'FORTALEZA MATERIALES, S.A.P.I. DE C.V.',
    'INSTITUTO DEL FONDO NACIONAL PARA EL CONSUMO DE LOS TRABAJADORES',
    'FONDO DE GARANTÍA Y FOMENTO PARA LA AGRICULTURA, GANADERÍA Y AVICULTURA',
    'FORD CREDIT DE MEXICO, S.A. DE C.V., SOFOM, E.R.',
    'FINANCIERA BEPENSA, S.A. DE C.V., SOFOM, E.R.',
    'FERROCARRIL MEXICANO, S.A. DE C.V.',
    'FONDO ESPECIAL PARA FINANCIAMIENTOS AGROPECUARIOS',
    'ELEMENTIA MATERIALES, S.A.P.I. DE C.V.',
    'BANCO COMPARTAMOS, S.A., INSTITUCION DE BANCA MULTIPLE',
    'CONCESIONARIA MEXIQUENSE, S.A. DE C.V.',
    'FACTORING CORPORATIVO, S.A. DE C.V., SOFOM, E.R.',
    'GRUPO COLLADO S.A. DE C.V.',
    'INVERSIONES CMPC S.A.',
    'COMERCIALIZADORA CÍRCULO CCK, S.A. DE C.V.',
    'CITIBANAMEX CASA DE BOLSA, S.A DE C.V., CASA DE BOLSA INTEGRANTE DEL GRUPO FINANCIERO CITIBANAMEX',
    'BANCA CREMI, S.A. INSTITUCION DE BANCA MULTIPLE',
    'COMISION FEDERAL DE ELECTRICIDAD',
    'CETELEM, S.A. DE C.V. SOFOM, E.R.',
    'BETTERWARE DE MÉXICO, S.A.P.I. DE C.V.',
    'BANCO LATINOAMERICANO DE COMERCIO EXTERIOR, S.A.',
    'BANCA MIFEL, S.A., INSTITUCIÓN DE BANCA MÚLTIPLE, GRUPO FINANCIERO MIFEL',
    'BANCO DE INVERSIÓN AFIRME, S.A. INSTITUCION DE BANCA MÚLTIPLE, AFIRME GRUPO FINANCIERO',
    'BEGRAND, S.A.P.I. DE C.V.',
    'BBVA LEASING MEXICO, S.A. DE C.V.',
    'BEPENSA BEBIDAS S.A. DE C.V.',
    'BANCO BASE, S.A., INSTITUCIÓN DE BANCA MÚLTIPLE, GRUPO FINANCIERO BASE',
    'BANCO MERCANTIL DEL NORTE, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO BANORTE',
    'BANCO NACIONAL DE OBRAS Y SERVICIOS PUBLICOS SOCIEDAD NACIONAL DE CREDITO INSTITUCION DE BANCA DE DESARROLLO',
    'BANCA AFIRME, S.A., INSTITUCION DE BANCA MULTIPLE, AFIRME GRUPO FINANCIERO',
    'BANCO ACTINVER, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO ACTINVER',
    'GRUPO AXO, S.A.P.I DE C.V.',
    'ARRENDADORA ACTINVER, S.A. DE C.V.',
    'ALMACENADORA MERCADER, S.A., ORGANIZACIÓN AUXILIAR DEL CRÉDITO',
    'BBVA BANCOMER, S.A. INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO BBVA BANCOMER',
    'FACTORAJE AFIRME, S.A. DE C.V., SOFOM, E.R., AFIRME GRUPO FINANCIERO',
    'ARRENDADORA AFIRME S.A. DE C.V., SOFOM, E.R., AFIRME GRUPO FINANCIERO',
    'ALMACENADORA AFIRME S.A. DE C.V., ORGANIZACION AUXILIAR DEL CRÉDITO, AFIRME GRUPO FINANCIERO',
    'BANCO DEL BAJÍO, S.A. INSTITUCIÓN DE BANCA MÚLTIPLE, GRUPO FINANCIERO DEL BAJÍO'
    ]

list_top_500 = [
    "Petróleos Mexicanos",
    "América Móvil",
    "Walmart de México",
    "Comisión Federal de Electricidad",
    "FEMSA",
    "General Motors de México",
    "Grupo Bimbo",
    "Alfa",
    "Grupo México",
    "Cemex",
    "Grupo Financiero BBVA Bancomer",
    "Stellantis México",
    "Grupo BAL",
    "Americas Mining Corporation",
    "Grupo Coppel",
    "Grupo Financiero Banorte",
    "Kaluz",
    "Ternium México",
    "FEMSA Comercio (Oxxo)",
    "Ford de México",
    "Coca-Cola FEMSA",
    "Grupo Salinas",
    "Grupo Comercial Chedraui",
    "Arca Continental",
    "Nissan Mexicana",
    "Infonavit",
    "Orbia Advance Corporation",
    "Volkswagen de México",
    "Toyota Motor Sales de México",
    "Grupo Financiero Citibanamex",
    "Alpek",
    "Organización Soriana",
    "El Puerto de Liverpool",
    "Sam's Club",
    "Grupo Elektra",
    "Sigma Alimentos",
    "Honda de México",
    "Grupo Financiero Santander México",
    "Industrias Peñoles",
    "Grupo Carso",
    "Grupo Modelo AB-InBev",
    "Grupo Televisa",
    "KIA Motors México",
    "Gruma",
    "Heineken México",
    "Jabil Circuit de México",
    "PepsiCo Alimentos México",
    "Samsung México",
    "Flextronics Manufacturing México",
    "Corporativo Fragua",
    "Grupo Xignux",
    "Iberdrola México",
    "Mabe",
    "Grupo Lala",
    "Industrias Bachoco",
    "Grupo Villacero",
    "Magna International México",
    "Nemak",
    "GNP",
    "Nestlé México",
    "Continental México",
    "FEMSA División Salud",
    "Banco Azteca",
    "Grupo Financiero HSBC",
    "Grupo Financiero Inbursa",
    "Tiendas Elektra",
    "Robert Bosch México",
    "SuKarne",
    "DeAcero",
    "MetLife México",
    "Industrias CH",
    "Costco de México",
    "Archer Daniels Midland México (ADM)",
    "Cinépolis",
    "Grupo Desc",
    "Grupo Empresarial Ángeles",
    "Grupo Financiero Scotiabank Inverlat",
    "AT&T México",
    "Grupo Simec",
    "Fresnillo PLC",
    "Alsea",
    "Grupo Sanborns",
    "Grupo Proeza",
    "Grupo México División Transportes",
    "Banobras",
    "Lear Corporation México",
    "Casa Ley",
    "Grupo Envases Universales",
    "Union Pacific de México",
    "Televisa Telecomunicaciones",
    "P&G México",
    "ArcelorMittal México",
    "Farmacias del Ahorro",
    "Kimberly-Clark de México",
    "Seguros BBVA Bancomer",
    "Adient México",
    "Altos Hornos de México",
    "Grupo Aeroméxico",
    "AXA Seguros",
    "The Home Depot México",
    "H-E-B México",
    "Volaris",
    "Grupo Condumex",
    "Viakable",
    "Valeo México",
    "Grupo Ángeles Servicios de Salud",
    "American Axle Manufacturing de México",
    "Naturgy México",
    "Caminos y Puentes Federales (Capufe)",
    "Bio PAPPEL",
    "FEMSA Combustibles",
    "Vitro",
    "Jose Cuervo",
    "Sanmina-SCI de México",
    "Quálitas Controladora",
    "IEnova México",
    "Grupo Palacio de Hierro",
    "Johnson Controls México",
    "Kenworth Mexicana",
    "Televisa Contenidos",
    "BorgWarner México",
    "Pilgrim's Pride México",
    "Seguros Monterrey New York Life",
    "Mondeléz México",
    "A.P. Moller Maersk México",
    "INTERprotección",
    "LyondellBasell de México",
    "Grupo Profuturo",
    "MAPFRE México",
    "Hyundai Motor de México",
    "Aeropuertos y Servicios Auxiliares",
    "La Comer",
    "Grupo Gigante",
    "Zurich México",
    "Afirme Grupo Financiero",
    "AMResorts",
    "Totalplay",
    "Seguros Banorte",
    "Kansas City Southern de México",
    "Telefónica Movistar",
    "Grupo Lamosa",
    "Unilever de México",
    "Grupo Herdez",
    "CICSA",
    "Elementia",
    "Grupo Bafar",
    "Grupo Petroil",
    "Johnson & Johnson México",
    "Gentera",
    "Fovissste",
    "Holcim México",
    "Nafin",
    "Megacable Holdings",
    "Sears México",
    "Citibanamex Seguros",
    "Danone de México",
    "Dow Química Mexicana",
    "Braskem Idesa SAPI",
    "Smurfit Kappa México",
    "Mercado Libre de México",
    "Ingredion México",
    "Tiendas 3B",
    "Cooperativa La Cruz Azu",
    "PPG Comex",
    "Plastic Omnium México",
    "Alpura",
    "Prolec",
    "GE México",
    "Pensiones Banorte",
    "Banco del Bajío",
    "Sky",
    "Fibra Uno",
    "Grupo Autofin México",
    "Rassini",
    "Seguros Inbursa",
    "Industrias Martinrea de México",
    "Grupo Cementos de Chihuahua",
    "Mars México",
    "Marzam",
    "Grupo Inditex México",
    "IDEAL",
    "Tenneco México",
    "Qualtia Alimentos",
    "Viva Aerobus",
    "Grupo Industrial Saltillo",
    "Chubb Seguros México",
    "Amazon México",
    "Shell México",
    "Grupo Vidanta",
    "GAP (Grupo Aeroportuario del Pacífico)",
    "Bepensa",
    "Grupo Cuprum",
    "Softtek",
    "ASUR (Grupo Aeroportuario de Sureste)",
    "Grupo Surman",
    "Cummins México México",
    "Navistar International de México",
    "Crown Envases México",
    "Office Depot de México",
    "Conservas La Costeña",
    "Philip Morris México",
    "Grupo Jumex",
    "Seguros Atlas",
    "Bancomext",
    "Minera Media Luna",
    "Bayer de México",
    "Grupo Traxión",
    "Banregio",
    "Empresas Cablevisión",
    "Allianz México",
    "Brookfield Business Partners México",
    "Henkel Mexicana",
    "Mazda Motor de México",
    "Grupo Axo",
    "Nexteer Automotive México",
    "Tiendas Neto",
    "Corporación Moctezuma",
    "Grupo Pinsa",
    "Posco México",
    "Genomma Lab Internacional",
    "Casa de Bolsa Banorte Ixe",
    "Siemens México",
    "Superior Industries de México",
    "Profuturo Pensiones",
    "Diconsa",
    "BanCoppel",
    "Farmacias Benavides",
    "Zurich Santander Seguros México",
    "Sanofi México",
    "Avon Cosmetics México",
    "Essity México",
    "Grupo La Moderna",
    "3M México",
    "Sociedad Hipotecaria Federal",
    "NR Finance México",
    "Ishop & Mixup",
    "Almidones Mexicanos",
    "Grupo Hermes",
    "Monex SAB",
    "ALPLA México",
    "Grupo Kaltex",
    "Crédito Real",
    "The Chemours Company Mexicana",
    "Vista Oil & Gas",
    "Newmont Goldcorp de México",
    "Grupo Omnilife",
    "TV Azteca",
    "Minera Frisco",
    "Grupo Collado",
    "Volkswagen Financial Services",
    "Emerson Electric de México",
    "Linde México",
    "Aeropuerto Internacional de la CDMX",
    "Pinfra",
    "Interceramic",
    "TPI Composites México",
    "Grupo GP",
    "Grupo Altex",
    "Grupo Premier",
    "Cooper-Standard Automotive de México",
    "Cinemex",
    "Banjército",
    "Omega CORP",
    "Unifin Financiera",
    "Bridgestone de México",
    "Katcon Global",
    "Gestamp Holding México",
    "First Cash",
    "Axtel",
    "Cydsa",
    "México Proyectos y Desarrollos",
    "Peña Verde",
    "Evraz NA México",
    "Red de Carreteras de Occidente",
    "Penske México",
    "ABB México",
    "RUBA Inmobiliaria",
    "Laureate Education México",
    "Invex Controladora",
    "Aleatica",
    "Grupo Peñafiel",
    "Rotoplas",
    "Grupo Mexicano de Seguros",
    "Roche México",
    "Circle K México",
    "American Tower México",
    "Absormex CMPC Tissue",
    "Grupo Accel",
    "L'Oréal México",
    "Kentucky Fried Chicken",
    "Seguros Afirme",
    "Herbalife Internacional de México",
    "Intercam Grupo Financiero",
    "Grupo Financiero Ve por Más",
    "AES México",
    "GM Financial de México",
    "Betterware de México",
    "British American Tobacco México",
    "Kellogg Company México",
    "BMW de México",
    "The Andersons México",
    "SAP México",
    "Pensiones BBVA Bancomer",
    "Corporación Actinver",
    "TC Energy México",
    "Corporación First Majestic",
    "Pan American Silver Corp.",
    "Coconal",
    "Pronósticos para la Asistencia Pública",
    "American Express Bank México",
    "Arcos Dorados México",
    "Arauco Industrias México",
    "Pfizer México",
    "Compañía Minera Autlán",
    "Canel's",
    "Christus Muguerza",
    "Grupo Indi",
    "Ferrero de México",
    "Grupo Pochteca",
    "Suzuki Motor de México",
    "Telesites",
    "Universal Scientific Industrial de México",
    "Reaseguradora Patria",
    "Caja Popular Mexicana",
    "OMA (Grupo Aeroportuario del Centro Norte)",
    "Molymex",
    "Dulces de la Rosa",
    "HDI Seguros",
    "Inmuebles Carso",
    "Servicio Panamericano de Proteccion",
    "Diageo México",
    "Agnico Eagle México",
    "Plexus Electronica",
    "Teleperformance México",
    "Greenbrier México",
    "Yara México",
    "Afore XXI Banorte",
    "H&M México",
    "Manpower México",
    "Schneider Electric México",
    "Mitsubishi Motors de México",
    "Javer",
    "Grupo Marítimo Industrial",
    "Concesionaria Mexiquense",
    "Boehringer Ingelheim México",
    "CIBanco",
    "Grupo Posadas",
    "Grupo GIA",
    "Grupo Financiero Multiva",
    "Ryder de México",
    "Fábrica de Papel San Francisco",
    "Grupo Financiero Mifel Controladora",
    "Avient de México",
    "Sandvik Mexicana",
    "Autotransportes de Carga Tresguerras",
    "Global HITSS",
    "J.P. Morgan Grupo Financiero",
    "Brembo México",
    "Argonaut Gold de México",
    "Grupo Pueblo Bonito",
    "Grupo Celanese",
    "Bank of America México",
    "Profuturo Afores",
    "Fonacot",
    "Citibanamex Afore",
    "CompuSoluciones",
    "Renault México",
    "Grupo Imagen Medios de Comunicación",
    "Coeur Mining Mexicana",
    "HSBC Seguros",
    "Consorcio ARA",
    "Novartis México",
    "Ontex México - P.I. Mabe",
    "Afore Sura",
    "Tupy México",
    "Acciona México",
    "AstraZeneca",
    "Farmacéuticos Maypo",
    "Seguros Sura",
    "Grupo Adecco México",
    "Daimler México",
    "Banco Sabadell México",
    "RLH Properties",
    "Grupo Minsa",
    "CFE Capital",
    "Grupo Financiero BASE",
    "Grupo Caliente",
    "Leggett & Platt de México",
    "Atento México",
    "SKF de México",
    "Hershey's México",
    "CHEP México",
    "Promotora Ambiental",
    "Provident México",
    "Birmex",
    "AIG Seguros México",
    "Kimball Electronics México",
    "TI Group Automotive Systems México",
    "Mota-Engil México",
    "Super del Norte",
    "Toyota Financial Services México",
    "Bausch Health México",
    "Solvay México",
    "Actinver Casa de Bolsa",
    "Yakult México",
    "Enel México",
    "Dish de México",
    "Capstone México Mining Corp.",
    "MG Motor México",
    "Merck México",
    "Bonatti México",
    "Seguros Azteca",
    "Cetelem",
    "Organización Cultiba",
    "Fibra Prologis",
    "Playa Hotels & Resorts México",
    "Liconsa",
    "Grupo Vasconia",
    "Financiera Independencia",
    "Fibra Danhos",
    "Vector Casa de Bolsa",
    "Pascual Boing",
    "Banco del Bienestar",
    "Financiera Nacional de Desarrollo",
    "GlaxoSmithKline",
    "Arcosa Industries de México",
    "Howmet Aerospace México",
    "Conagra Brands",
    "PAM Transport México",
    "Corp. Interamericana de Entretenimiento",
    "Restaurantes Toks",
    "Alamos Gold",
    "Axalta Coating Systems México",
    "Wabtec de México",
    "Agroasemex",
    "Fortuna Silver Mines México",
    "Autobuses IAMSA",
    "Grupo Gayosso",
    "GMD (Grupo Mexicano de Desarrollo)",
    "Eli Lilly de México",
    "Inversora Bursátil Casa de Bolsa",
    "Fibra Educa",
    "Sistema de Transporte Colectivo",
    "Finamex Casa de Bolsa",
    "Vinte Inmobiliaria",
    "Grupo GICSA",
    "Stabilus México",
    "ArvinMeritor de México",
    "Fibra Terrafina",
    "Epiroc México",
    "Hydro Aluminium México",
    "Grupo Royal Holiday",
    "Bolsa Mexicana de Valores",
    "Médica Sur",
    "Codere México",
    "Fibra Macquarie México",
    "Assa Abloy México",
    "Meliá Hotels International",
    "Compañía Mexicana de Exploraciones",
    "Adelnor Grupo Empresarial",
    "Grupo Senda",
    "Great Panther Mining México",
    "Grupo HYCSA",
    "Dongkuk Steel México",
    "BUPA México",
    "Grupo Famsa",
    "Helvex",
    "Grupo Witt Automotriz",
    "Tupperware Brands México",
    "Scotia Inverlat Casa de Bolsa",
    "Grupo Financiero Aserta",
    "Monex Casa de Bolsa",
    "Nabors Perforaciones de México",
    "JK Tornel",
    "Corporación Inmobiliaria Vesta",
    "Bansí",
    "Exportadora de Sal",
    "Werner de México",
    "Dana de México Corporación",
    "FM Global de México",
    "Caffenio",
    "FCA Financial Mexico",
    "Seguros Ve por Más",
    "Veolia México",
    "RHI Magnesita de México",
    "FibraHotel",
    "Grupo Multisistemas de Seguridad Industrial",
    "Brown-Forman Tequila México",
    "Value Grupo Financiero",
    "Seguros Argos",
    "Aranzazu - Aura Minerals",
    "Corpovael Inmobiliaria",
    "Goldman Sachs Casa de Bolsa",
    "CCL Industries México",
    "KUA",
    "Park-Ohio de México",
    "Grupo AGGALL - Coliman",
    "Axity",
    "Hospitales MAC",
    "Kavak"
]


print(len(list_to_compare))
print(len(list_top_500))

list_to_compare = [word.lower() for word in list_to_compare]
list_top_500 = [word.lower() for word in list_top_500]


from difflib import get_close_matches, SequenceMatcher
import pandas

def create_dictionary(first_list, second_list):
    dictionary = {}
    for word in first_list:
        closest_match, percentage = get_closest_match(word, second_list)
        if closest_match is not None:
            dictionary[word] = {'List500': closest_match, 'similarity_%': percentage}
    return dictionary

def get_closest_match(word, second_list):
    highest_similarity = 0
    closest_match = None
    i = 0
    for candidate in second_list:
        i += 1
        # print(i)
        similarity = similarity_percentage(word, candidate)
        if similarity > highest_similarity:
            highest_similarity = similarity
            closest_match = candidate
    return closest_match, highest_similarity

def similarity_percentage(string1, string2):
    matcher = SequenceMatcher(None, string1, string2)
    return matcher.ratio() * 100

# Пример использования
first_list = ["apple", "banana", "orange"]
second_list = ["apricot","bananoa", "banana", "grape", "orange", "applo"]

print(list_to_compare[0])
print(list_top_500[0])

result_dictionary = create_dictionary(first_list, second_list)
print(result_dictionary)

result_dictionary = create_dictionary(list_to_compare, list_top_500)
print(result_dictionary)
print(len(result_dictionary))

df = pd.DataFrame.from_dict(result_dictionary, orient='index')
df.to_excel('output.xlsx')