    "Petróleos Mexicanos",
    "América Móvil",
    "Walmart de México",
    "Comisión Federal de Electricidad",
    "FEMSA",
    "General Motors de México",
    "Grupo Bimbo",
    "Alfa",
    "Grupo México",
    "Cemex",
    "Grupo Financiero BBVA Bancomer",
    "Stellantis México",
    "Grupo BAL",
    "Americas Mining Corporation",
    "Grupo Coppel",
    "Grupo Financiero Banorte",
    "Kaluz",
    "Ternium México",
    "FEMSA Comercio (Oxxo)",
    "Ford de México",
    "Coca-Cola FEMSA",
    "Grupo Salinas",
    "Grupo Comercial Chedraui",
    "Arca Continental",
    "Nissan Mexicana",
    "Infonavit",
    "Orbia Advance Corporation",
    "Volkswagen de México",
    "Toyota Motor Sales de México",
    "Grupo Financiero Citibanamex",
    "Alpek",
    "Organización Soriana",
    "El Puerto de Liverpool",
    "Sam's Club",
    "Grupo Elektra",
    "Sigma Alimentos",
    "Honda de México",
    "Grupo Financiero Santander México",
    "Industrias Peñoles",
    "Grupo Carso",
    "Grupo Modelo AB-InBev",
    "Grupo Televisa",
    "KIA Motors México",
    "Gruma",
    "Heineken México",
    "Jabil Circuit de México",
    "PepsiCo Alimentos México",
    "Samsung México",
    "Flextronics Manufacturing México",
    "Corporativo Fragua",
    "Grupo Xignux",
    "Iberdrola México",
    "Mabe",
    "Grupo Lala",
    "Industrias Bachoco",
    "Grupo Villacero",
    "Magna International México",
    "Nemak",
    "GNP",
    "Nestlé México",
    "Continental México",
    "FEMSA División Salud",
    "Banco Azteca",
    "Grupo Financiero HSBC",
    "Grupo Financiero Inbursa",
    "Tiendas Elektra",
    "Robert Bosch México",
    "SuKarne",
    "DeAcero",
    "MetLife México",
    "Industrias CH",
    "Costco de México",
    "Archer Daniels Midland México (ADM)",
    "Cinépolis",
    "Grupo Desc",
    "Grupo Empresarial Ángeles",
    "Grupo Financiero Scotiabank Inverlat",
    "AT&T México",
    "Grupo Simec",
    "Fresnillo PLC",
    "Alsea",
    "Grupo Sanborns",
    "Grupo Proeza",
    "Grupo México División Transportes",
    "Banobras",
    "Lear Corporation México",
    "Casa Ley",
    "Grupo Envases Universales",
    "Union Pacific de México",
    "Televisa Telecomunicaciones",
    "P&G México",
    "ArcelorMittal México",
    "Farmacias del Ahorro",
    "Kimberly-Clark de México",
    "Seguros BBVA Bancomer",
    "Adient México",
    "Altos Hornos de México",
    "Grupo Aeroméxico",
    "AXA Seguros",
    "The Home Depot México",
    "H-E-B México",
    "Volaris",
    "Grupo Condumex",
    "Viakable",
    "Valeo México",
    "Grupo Ángeles Servicios de Salud",
    "American Axle Manufacturing de México",
    "Naturgy México",
    "Caminos y Puentes Federales (Capufe)",
    "Bio PAPPEL",
    "FEMSA Combustibles",
    "Vitro",
    "Jose Cuervo",
    "Sanmina-SCI de México",
    "Quálitas Controladora",
    "IEnova México",
    "Grupo Palacio de Hierro",
    "Johnson Controls México",
    "Kenworth Mexicana",
    "Televisa Contenidos",
    "BorgWarner México",
    "Pilgrim's Pride México",
    "Seguros Monterrey New York Life",
    "Mondeléz México",
    "A.P. Moller Maersk México",
    "INTERprotección",
    "LyondellBasell de México",
    "Grupo Profuturo",
    "MAPFRE México",
    "Hyundai Motor de México",
    "Aeropuertos y Servicios Auxiliares",
    "La Comer",
    "Grupo Gigante",
    "Zurich México",
    "Afirme Grupo Financiero",
    "AMResorts",
    "Totalplay",
    "Seguros Banorte",
    "Kansas City Southern de México",
    "Telefónica Movistar",
    "Grupo Lamosa",
    "Unilever de México",
    "Grupo Herdez",
    "CICSA",
    "Elementia",
    "Grupo Bafar",
    "Grupo Petroil",
    "Johnson & Johnson México",
    "Gentera",
    "Fovissste",
    "Holcim México",
    "Nafin",
    "Megacable Holdings",
    "Sears México",
    "Citibanamex Seguros",
    "Danone de México",
    "Dow Química Mexicana",
    "Braskem Idesa SAPI",
    "Smurfit Kappa México",
    "Mercado Libre de México",
    "Ingredion México",
    "Tiendas 3B",
    "Cooperativa La Cruz Azu",
    "PPG Comex",
    "Plastic Omnium México",
    "Alpura",
    "Prolec",
    "GE México",
    "Pensiones Banorte",
    "Banco del Bajío",
    "Sky",
    "Fibra Uno",
    "Grupo Autofin México",
    "Rassini",
    "Seguros Inbursa",
    "Industrias Martinrea de México",
    "Grupo Cementos de Chihuahua",
    "Mars México",
    "Marzam",
    "Grupo Inditex México",
    "IDEAL",
    "Tenneco México",
    "Qualtia Alimentos",
    "Viva Aerobus",
    "Grupo Industrial Saltillo",
    "Chubb Seguros México",
    "Amazon México",
    "Shell México",
    "Grupo Vidanta",
    "GAP (Grupo Aeroportuario del Pacífico)",
    "Bepensa",
    "Grupo Cuprum",
    "Softtek",
    "ASUR (Grupo Aeroportuario de Sureste)",
    "Grupo Surman",
    "Cummins México México",
    "Navistar International de México",
    "Crown Envases México",
    "Office Depot de México",
    "Conservas La Costeña",
    "Philip Morris México",
    "Grupo Jumex",
    "Seguros Atlas",
    "Bancomext",
    "Minera Media Luna",
    "Bayer de México",
    "Grupo Traxión",
    "Banregio",
    "Empresas Cablevisión",
    "Allianz México",
    "Brookfield Business Partners México",
    "Henkel Mexicana",
    "Mazda Motor de México",
    "Grupo Axo",
    "Nexteer Automotive México",
    "Tiendas Neto",
    "Corporación Moctezuma",
    "Grupo Pinsa",
    "Posco México",
    "Genomma Lab Internacional",
    "Casa de Bolsa Banorte Ixe",
    "Siemens México",
    "Superior Industries de México",
    "Profuturo Pensiones",
    "Diconsa",
    "BanCoppel",
    "Farmacias Benavides",
    "Zurich Santander Seguros México",
    "Sanofi México",
    "Avon Cosmetics México",
    "Essity México",
    "Grupo La Moderna",
    "3M México",
    "Sociedad Hipotecaria Federal",
    "NR Finance México",
    "Ishop & Mixup",
    "Almidones Mexicanos",
    "Grupo Hermes",
    "Monex SAB",
    "ALPLA México",
    "Grupo Kaltex",
    "Crédito Real",
    "The Chemours Company Mexicana",
    "Vista Oil & Gas",
    "Newmont Goldcorp de México",
    "Grupo Omnilife",
    "TV Azteca",
    "Minera Frisco",
    "Grupo Collado",
    "Volkswagen Financial Services",
    "Emerson Electric de México",
    "Linde México",
    "Aeropuerto Internacional de la CDMX",
    "Pinfra",
    "Interceramic",
    "TPI Composites México",
    "Grupo GP",
    "Grupo Altex",
    "Grupo Premier",
    "Cooper-Standard Automotive de México",
    "Cinemex",
    "Banjército",
    "Omega CORP",
    "Unifin Financiera",
    "Bridgestone de México",
    "Katcon Global",
    "Gestamp Holding México",
    "First Cash",
    "Axtel",
    "Cydsa",
    "México Proyectos y Desarrollos",
    "Peña Verde",
    "Evraz NA México",
    "Red de Carreteras de Occidente",
    "Penske México",
    "ABB México",
    "RUBA Inmobiliaria",
    "Laureate Education México",
    "Invex Controladora",
    "Aleatica",
    "Grupo Peñafiel",
    "Rotoplas",
    "Grupo Mexicano de Seguros",
    "Roche México",
    "Circle K México",
    "American Tower México",
    "Absormex CMPC Tissue",
    "Grupo Accel",
    "L'Oréal México",
    "Kentucky Fried Chicken",
    "Seguros Afirme",
    "Herbalife Internacional de México",
    "Intercam Grupo Financiero",
    "Grupo Financiero Ve por Más",
    "AES México",
    "GM Financial de México",
    "Betterware de México",
    "British American Tobacco México",
    "Kellogg Company México",
    "BMW de México",
    "The Andersons México",
    "SAP México",
    "Pensiones BBVA Bancomer",
    "Corporación Actinver",
    "TC Energy México",
    "Corporación First Majestic",
    "Pan American Silver Corp.",
    "Coconal",
    "Pronósticos para la Asistencia Pública",
    "American Express Bank México",
    "Arcos Dorados México",
    "Arauco Industrias México",
    "Pfizer México",
    "Compañía Minera Autlán",
    "Canel's",
    "Christus Muguerza",
    "Grupo Indi",
    "Ferrero de México",
    "Grupo Pochteca",
    "Suzuki Motor de México",
    "Telesites",
    "Universal Scientific Industrial de México",
    "Reaseguradora Patria",
    "Caja Popular Mexicana",
    "OMA (Grupo Aeroportuario del Centro Norte)",
    "Molymex",
    "Dulces de la Rosa",
    "HDI Seguros",
    "Inmuebles Carso",
    "Servicio Panamericano de Proteccion",
    "Diageo México",
    "Agnico Eagle México",
    "Plexus Electronica",
    "Teleperformance México",
    "Greenbrier México",
    "Yara México",
    "Afore XXI Banorte",
    "H&M México",
    "Manpower México",
    "Schneider Electric México",
    "Mitsubishi Motors de México",
    "Javer",
    "Grupo Marítimo Industrial",
    "Concesionaria Mexiquense",
    "Boehringer Ingelheim México",
    "CIBanco",
    "Grupo Posadas",
    "Grupo GIA",
    "Grupo Financiero Multiva",
    "Ryder de México",
    "Fábrica de Papel San Francisco",
    "Grupo Financiero Mifel Controladora",
    "Avient de México",
    "Sandvik Mexicana",
    "Autotransportes de Carga Tresguerras",
    "Global HITSS",
    "J.P. Morgan Grupo Financiero",
    "Brembo México",
    "Argonaut Gold de México",
    "Grupo Pueblo Bonito",
    "Grupo Celanese",
    "Bank of America México",
    "Profuturo Afores",
    "Fonacot",
    "Citibanamex Afore",
    "CompuSoluciones",
    "Renault México",
    "Grupo Imagen Medios de Comunicación",
    "Coeur Mining Mexicana",
    "HSBC Seguros",
    "Consorcio ARA",
    "Novartis México",
    "Ontex México - P.I. Mabe",
    "Afore Sura",
    "Tupy México",
    "Acciona México",
    "AstraZeneca",
    "Farmacéuticos Maypo",
    "Seguros Sura",
    "Grupo Adecco México",
    "Daimler México",
    "Banco Sabadell México",
    "RLH Properties",
    "Grupo Minsa",
    "CFE Capital",
    "Grupo Financiero BASE",
    "Grupo Caliente",
    "Leggett & Platt de México",
    "Atento México",
    "SKF de México",
    "Hershey's México",
    "CHEP México",
    "Promotora Ambiental",
    "Provident México",
    "Birmex",
    "AIG Seguros México",
    "Kimball Electronics México",
    "TI Group Automotive Systems México",
    "Mota-Engil México",
    "Super del Norte",
    "Toyota Financial Services México",
    "Bausch Health México",
    "Solvay México",
    "Actinver Casa de Bolsa",
    "Yakult México",
    "Enel México",
    "Dish de México",
    "Capstone México Mining Corp.",
    "MG Motor México",
    "Merck México",
    "Bonatti México",
    "Seguros Azteca",
    "Cetelem",
    "Organización Cultiba",
    "Fibra Prologis",
    "Playa Hotels & Resorts México",
    "Liconsa",
    "Grupo Vasconia",
    "Financiera Independencia",
    "Fibra Danhos",
    "Vector Casa de Bolsa",
    "Pascual Boing",
    "Banco del Bienestar",
    "Financiera Nacional de Desarrollo",
    "GlaxoSmithKline",
    "Arcosa Industries de México",
    "Howmet Aerospace México",
    "Conagra Brands",
    "PAM Transport México",
    "Corp. Interamericana de Entretenimiento",
    "Restaurantes Toks",
    "Alamos Gold",
    "Axalta Coating Systems México",
    "Wabtec de México",
    "Agroasemex",
    "Fortuna Silver Mines México",
    "Autobuses IAMSA",
    "Grupo Gayosso",
    "GMD (Grupo Mexicano de Desarrollo)",
    "Eli Lilly de México",
    "Inversora Bursátil Casa de Bolsa",
    "Fibra Educa",
    "Sistema de Transporte Colectivo",
    "Finamex Casa de Bolsa",
    "Vinte Inmobiliaria",
    "Grupo GICSA",
    "Stabilus México",
    "ArvinMeritor de México",
    "Fibra Terrafina",
    "Epiroc México",
    "Hydro Aluminium México",
    "Grupo Royal Holiday",
    "Bolsa Mexicana de Valores",
    "Médica Sur",
    "Codere México",
    "Fibra Macquarie México",
    "Assa Abloy México",
    "Meliá Hotels International",
    "Compañía Mexicana de Exploraciones",
    "Adelnor Grupo Empresarial",
    "Grupo Senda",
    "Great Panther Mining México",
    "Grupo HYCSA",
    "Dongkuk Steel México",
    "BUPA México",
    "Grupo Famsa",
    "Helvex",
    "Grupo Witt Automotriz",
    "Tupperware Brands México",
    "Scotia Inverlat Casa de Bolsa",
    "Grupo Financiero Aserta",
    "Monex Casa de Bolsa",
    "Nabors Perforaciones de México",
    "JK Tornel",
    "Corporación Inmobiliaria Vesta",
    "Bansí",
    "Exportadora de Sal",
    "Werner de México",
    "Dana de México Corporación",
    "FM Global de México",
    "Caffenio",
    "FCA Financial Mexico",
    "Seguros Ve por Más",
    "Veolia México",
    "RHI Magnesita de México",
    "FibraHotel",
    "Grupo Multisistemas de Seguridad Industrial",
    "Brown-Forman Tequila México",
    "Value Grupo Financiero",
    "Seguros Argos",
    "Aranzazu - Aura Minerals",
    "Corpovael Inmobiliaria",
    "Goldman Sachs Casa de Bolsa",
    "CCL Industries México",
    "KUA",
    "Park-Ohio de México",
    "Grupo AGGALL - Coliman",
    "Axity",
    "Hospitales MAC",
    "Kavak"
